/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphproject;

import java.awt.Frame;
import javax.swing.JOptionPane;


/**k00231373
 *
 * @author Jacynta
 */
public class AirportsGUI extends javax.swing.JFrame {
Graph airport;
String departFrom;
String arriveIn;   
int distance;
Frame f;
    
    /**
     * Creates new form AirportsGUI
     */
    public AirportsGUI() {
        initComponents();
         airport = new Graph();
        airport.InitialiseAirports();
        String text = airport.PrintFlights();
        FlightSchedTxtArea.setText(text);
         Frame f = new Frame("pupup win");

  f.setSize(200,200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDepAirport = new javax.swing.JLabel();
        lblArrivalAir = new javax.swing.JLabel();
        lblDistance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightSchedTxtArea = new javax.swing.JTextArea();
        bttnAddFlight = new javax.swing.JButton();
        bttnSeekFlight = new javax.swing.JButton();
        bttnDeleteFlight = new javax.swing.JButton();
        bttnExit = new javax.swing.JButton();
        txtBoxDepartureAirport = new javax.swing.JTextField();
        txtBoxArrivalAirport = new javax.swing.JTextField();
        txtBoxDistance = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightInfoTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("AirportFrame"); // NOI18N

        lblDepAirport.setText("Departure Airport");

        lblArrivalAir.setText("Arrival Airport");

        lblDistance.setText("Distance");

        FlightSchedTxtArea.setEditable(false);
        FlightSchedTxtArea.setBackground(new java.awt.Color(204, 255, 204));
        FlightSchedTxtArea.setColumns(20);
        FlightSchedTxtArea.setRows(5);
        FlightSchedTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N
        jScrollPane1.setViewportView(FlightSchedTxtArea);

        bttnAddFlight.setText("Add New Flight");
        bttnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddFlightActionPerformed(evt);
            }
        });

        bttnSeekFlight.setText("Seek Flight");
        bttnSeekFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSeekFlightActionPerformed(evt);
            }
        });

        bttnDeleteFlight.setText("Delete Flight");
        bttnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteFlightActionPerformed(evt);
            }
        });

        bttnExit.setText("Exit");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        txtBoxDepartureAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxDepartureAirportActionPerformed(evt);
            }
        });

        txtBoxArrivalAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxArrivalAirportActionPerformed(evt);
            }
        });

        txtBoxDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxDistanceActionPerformed(evt);
            }
        });

        FlightInfoTxtArea.setEditable(false);
        FlightInfoTxtArea.setBackground(new java.awt.Color(255, 255, 204));
        FlightInfoTxtArea.setColumns(20);
        FlightInfoTxtArea.setRows(5);
        FlightInfoTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 0, 153))); // NOI18N
        jScrollPane2.setViewportView(FlightInfoTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bttnAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnSeekFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnDeleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArrivalAir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBoxDepartureAirport, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtBoxArrivalAirport)
                            .addComponent(txtBoxDistance))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxDepartureAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepAirport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxArrivalAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArrivalAir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistance)
                    .addComponent(txtBoxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnDeleteFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnSeekFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bttnAddFlight.getAccessibleContext().setAccessibleName("addFlight");
        bttnExit.getAccessibleContext().setAccessibleName("bttnExit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddFlightActionPerformed
//        departFrom = txtBoxDepartureAirport.getText();
//        arriveIn = txtBoxArrivalAirport.getText();
//        String weight = txtBoxDistance.getText();
        if(!airport.IsFull()){
        
        if(!txtBoxDistance.getText().isEmpty() && !txtBoxDepartureAirport.getText().isEmpty() && !txtBoxArrivalAirport.getText().isEmpty()){

        departFrom = txtBoxDepartureAirport.getText();
        arriveIn = txtBoxArrivalAirport.getText();
        String weight = txtBoxDistance.getText();
        distance = Integer.parseInt(weight);
        airport.AddVertex(departFrom);
        airport.AddVertex(arriveIn);
        airport.AddEdge(departFrom, arriveIn, distance);
        String text = airport.PrintFlights();
        FlightSchedTxtArea.setText(text);
        FlightInfoTxtArea.setText("Flight added");
        }
        else{
            JOptionPane.showMessageDialog(f," Fill in all flight info", "Warning " , JOptionPane.WARNING_MESSAGE);
        }
        }
        else
            FlightInfoTxtArea.setText("maximum flights added cannot add any more ");
    }//GEN-LAST:event_bttnAddFlightActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    
   
   
    private void txtBoxDepartureAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxDepartureAirportActionPerformed
          departFrom = txtBoxDepartureAirport.getText();
    }//GEN-LAST:event_txtBoxDepartureAirportActionPerformed

    private void txtBoxArrivalAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxArrivalAirportActionPerformed
         arriveIn = txtBoxArrivalAirport.getText();
    }//GEN-LAST:event_txtBoxArrivalAirportActionPerformed

    private void txtBoxDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxDistanceActionPerformed
        String weight = txtBoxDistance.getText();
         distance = Integer.parseInt(weight);
    }//GEN-LAST:event_txtBoxDistanceActionPerformed

    private void bttnSeekFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSeekFlightActionPerformed
        departFrom = txtBoxDepartureAirport.getText();
         arriveIn = txtBoxArrivalAirport.getText();
        String output = airport.Search(airport, departFrom, arriveIn);
        FlightInfoTxtArea.setText(output);
    }//GEN-LAST:event_bttnSeekFlightActionPerformed

    private void bttnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteFlightActionPerformed
        departFrom = txtBoxDepartureAirport.getText();
        arriveIn = txtBoxArrivalAirport.getText();
        String output = airport.RemoveFlight(departFrom,arriveIn);
        String text = airport.PrintFlights();
        FlightSchedTxtArea.setText(text);
        FlightInfoTxtArea.setText(output);
    }//GEN-LAST:event_bttnDeleteFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //Graph airport = new Graph();

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirportsGUI().setVisible(true);
                
               
            }
        });
        
         

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FlightInfoTxtArea;
    private javax.swing.JTextArea FlightSchedTxtArea;
    private javax.swing.JButton bttnAddFlight;
    private javax.swing.JButton bttnDeleteFlight;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnSeekFlight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArrivalAir;
    private javax.swing.JLabel lblDepAirport;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JTextField txtBoxArrivalAirport;
    private javax.swing.JTextField txtBoxDepartureAirport;
    private javax.swing.JTextField txtBoxDistance;
    // End of variables declaration//GEN-END:variables


}
